### ISSUE TITLE
Weird error messages during Blender import.

### ISSUE THREAD

**Issue by 0xBEEEF** [Syroot/Pod#1]
I cloned the repository, and imported the plugin into Blender. So far so good, if I want to import something now, then always comes the following error. No matter which track I take, it always happens. Any ideas?

```
Traceback (most recent call last):
  File "C:\Users\TestUser\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_bl4\importing.py", line 41, in execute
    self.convert()
  File "C:\Users\TestUser\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_bl4\importing.py", line 46, in convert
    self.convert_texture(texture, "Image{0:03d}".format(i), self.circuit.textures.size)
  File "C:\Users\TestUser\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_bl4\importing.py", line 73, in convert_texture
    b_links.new(b_texture_node.outputs['Color'], b_diffuse_node.inputs['Color'])
AttributeError: 'NoneType' object has no attribute 'inputs'
```

**Comment by RayKoopa** [comment]
Apparently your Blender configuration creates a different default Cycles material than mine.
The add-on currently bases on that default material as seen in my Blender, but I'll change that to completely reset the material and add the nodes manually, which would fix your issue.

**Comment by RayKoopa** [comment]
Can you check if it was fixed for you with https://github.com/Syroot/Pod/commit/5007572a02f3e9bff2bdda539bb5ad46c8eb67d8 ?

**Comment by 0xBEEEF** [comment]
Thank you for the quick adjustment. Unfortunately, it still doesn't work 100%. I can now import the 3D models, but the textures are not read correctly and added. As you can see on the right, there are textures, but they all have no content.
![blender](https://user-images.githubusercontent.com/36008527/41200718-51b94c20-6caa-11e8-8a11-9e953aa18ea2.jpg)

**Comment by RayKoopa** [comment]
You need to switch to the Cycles renderer. The add-on does not support the Blender Internal renderer anymore, as it has been removed from the upcoming 2.8 completely.

**Comment by 0xBEEEF** [comment]
Yes, it works now. Could you maybe put that in the readme document? I don't think many people are aware that the "Blender Renderer" menu is still at the top by default.

**Comment by RayKoopa** [comment]
A readme will be added at a later stage, right now the add-on is under heavy development. Since 2.8 will not even provide the combo box to select the renderer anymore (Cycles will be the only one left), the note may have become redundant by then.

**Comment by RayKoopa** [comment]
I further addressed this by additionally supporting Blender Internal.
The add-on imports materials fitting the currently selected render engine (Blender Game will still not be supported), so before you import, ensure to have your favorite engine selected.

**Comment by 0xBEEEF** [comment]
All right! I think it's really great that you write such a great plugin. It's just like in the old retro days. It is really fun to fly through the race tracks in Blender's flight mode and to see perspectives that you could never see in the game. Very impressive indeed. Now only the original lighting is missing, and the atmosphere is the same as before.

**Comment by RayKoopa** [comment]
You may wanna join the Discord server where I typically post interesting findings on the tracks (like a completely invisible but finished building in Alderon) :)

**Comment by 0xBEEEF** [comment]
@RayKoopa 
Sorry for the late answer. Thank you for your offer on the Discord Server. I'll see if I can get back to it and sign in. But I can't make any promises. 
I have a few follow-up questions. But before I put these, I would like to express my praise for your work. What you've accomplished here in a very short time is truly incredible. Perhaps you could say something about this for a moment. I read something about the game service in your repository. Would you like to resurrect this one? If so, I'd love that. Now you've already built a great importer for all the tracks. But in principle that is only one side of the coin. Are you planning to support the other side to be able to output the data again? I also noticed that at places where animated objects were in the game there is simply nothing at all. It would be great if you could also import the animations. You seem to know your way around here and have a lot of knowledge. It would be very nice if you could invest some more time and energy here, and could offer a little more here.

**Comment by RayKoopa** [comment]
Hey there, thanks for the praise.

About the game service, I'm not focussing it anymore. The last version really _integrated_ into Pod was 2.2.8.0 and beared no encryption whatsoever (your passwords were sent in plain text over the net). The 2.2.9.0 service used some pseudo-encryption (but nothing really secure) at least.
While that might be neglectible, hosting a server at home also doesn't work anymore because most connections now use DSLite which don't give you a real IPv4 address anymore, so nobody could connect to the server / you can't be the server). That's the reason why I stopped working on that.

About the add-on, I did plan to add exporting in the future. In fact, the C# library can already completely load, manipulate, and export tracks, just not in a "designing" way (just raw code). I got a bit lazy porting the C# library over to Python, so it's kinda paused at the moment.
In fact, animated objects are their own mesh, with each frame forming it's own mesh if required. It's currently not imported into Blender, the animations follow a lot later and thus weren't part of the efforts yet.
